### PR TITLE
Build on LTS-7

### LINKED ISSUE #199: Install fails with lts-7.0
[ LTS Haskell 7.0 (gcc-8.0.1)](https://www.stackage.org/lts-7.0) just came out and unfortunately this now seems to mean that haskell-vim-now does not install properly anymore. (I was able to trace the problem to the [codex](https://github.com/aloiscochard/codex) package, see [issue 63](https://github.com/aloiscochard/codex/issues/63#issuecomment-248896302)).

Here's where I think `haskell-vim-now` has a bug: Even if I carefully setup the global stack project (`.stack/global-project/`) to use LTS-6.12 via

```
stack --resolver lts-6.12 setup
```

so that I can successfully install the codex package via

```
stack --resolver lts-6.12 install codex
```

I still have a failure of 

```
bash /tmp/haskell-vim-now.sh
``` 

as follows:

```
...
...
--- Setting up GHC if needed...
Downloaded ghc-8.0.1.                                      
Installed GHC.                                                                 
	Stack bin path: /Users/mmayer/.local/bin
	Stack global path: /Users/mmayer/.stack
	Stack global config location: /Users/mmayer/.stack/global-project/stack.yaml
	Stack resolver: lts-7.0
	/Users/mmayer/.config/haskell-vim-now/.stack-bin -> /Users/mmayer/.local/bin
--- Installing helper binaries...
Plan construction failed.
*** Binary installation failed with error 1.
*** Aborting...
```

Somehow the scripts pick up LTS-7.0 (ghc-8.0.1) along the way, and the installation fails.

I'm using a clean Ubuntu VM, and I have the same issue on Mac OS X.

### PR DESCRIPTION
**Pull request by begriffs**
I added Mac tests along with Linux on Travis. Linux works OK but Mac hangs when running vim-plug. Any ideas?

Fixes #199

Also specifying a particular version of `codex` and some of its dependencies feels remarkably janky. We could choose another LTS version when installing helper binaries but that might cause a whole new GHC to be pulled down and compiled which would increase install time. Also building ghc-mod under a different version than the developer is likely to use would probably make it break on actual projects (it's finicky).

### CODE REVIEW

**Comment by begriffs** [comment]
I'm confused why the setup hangs on OS X on Travis. Any ideas?

**Comment by SX91** [comment]
I've had the same problem trying to port install script to haskell. It just hangs, no output, no logs. Didn't happen with real terminal emulators. Maybe it checks for $TERM?

**Comment by begriffs** [comment]
I don't know why it's hanging on the OS X tests so I'm planning to revert that build matrix work but leave the codex change to address the original reason for this pull request.

**Comment by begriffs** [comment]
I'm going to merge this despite the unpleasantness of hard-coding versions in the stack install command. Installation is currently broken on all platforms and I think this will fix it.

**Pull request merged**
