### PR TITLE
Add fix for windows-style paths stack-path returns

### LINKED ISSUE #98: Installing in cygwin
Tried installing it with cygwin (64 bit). I've found all the packages needed, but then I had this error with 7zip. Is it more of a stack problem?

	Preparing to download 7z.exe ...
	Already downloaded.
	C:\Users\d00ide\AppData\Local\Programs\stack\x86_64-windows\7z.exe: rawSystem: invalid argument (Invalid argument)
	--- Adding extra stack deps if needed
	sed: impossible de lire /home/d00ide/.stack/global-project/stack.yaml: No such file or directory
	sed: impossible de lire /home/d00ide/.stack/global/stack.yaml: No such file or directory
	sed: impossible de lire /home/d00ide/.stack/global-project/stack.yaml: No such file or directory
	sed: impossible de lire /home/d00ide/.stack/global/stack.yam: No such file or directory
	--- Installing helper binaries
	Run from outside a project, using implicit global project config
	Selected resolver: nightly-2015-11-17
	Downloading nightly-2015-11-17 build plan ...
	Downloaded nightly-2015-11-17 build plan.
	Caching build plan
	No compiler found, expected minor version match with ghc-7.10.2 (x86_64) (based on resolver setting in C:\Users\d00ide\AppData\Roaming\stack\global-project\stack.yaml).
	Try running "stack setup" to install the correct GHC into C:\Users\d00ide\AppData\Local\Programs\stack\x86_64-windows\
	--- Installing git-hscope
	cp: impossible de créer le fichier standard « /home/d00ide/.local/bin »: No such file or directory
	--- Building Hoogle database...
	/dev/fd/63: ligne 113: /home/d00ide/.local/bin/hoogle: No such file or directory
	--- Setting git to use fully-pathed vim for messages...
	--- Configuring codex to search in stack...

### PR DESCRIPTION
**Pull request by SimpleX91**
Attempt to fix cygwin installation problems. *Untested*.
Closes #98

### CODE REVIEW

**Comment by begriffs** [comment]
Thanks for the PR. I'm having trouble getting my Cygwin to work right in the VM. @ideruga could you help test this please?

**Comment by ideruga** [comment]
I'll try it this evening (E.T.)

**Comment by ideruga** [comment]
I ran bash <(curl -sL https://raw.githubusercontent.com/SimpleX91/haskell-vim-now/cygwin/install.sh) 2>haskell-vim-now-2015-12-01.log
I've attached the result.

I think that the problem is that cygwin doesn't recognize the path elements that start with C:\. It should start with /cygdrive/c. Also, there is the question of slash v.s. backslash. 

[haskell-vim-now-2015-12-01.txt](https://github.com/begriffs/haskell-vim-now/files/49205/haskell-vim-now-2015-12-01.txt)

**Comment by ideruga** [comment]
Ok, so I was right... I downloaded the file  https://raw.githubusercontent.com/SimpleX91/haskell-vim-now/cygwin/install.sh, changed the clone command to this:
>  https://raw.githubusercontent.com/SimpleX91/haskell-vim-now/cygwin/install.sh

and ran it this way:

> ./install.sh > haskell-vim-now-2015-12-01_b.txt 2>&1

I think that ^M spoils all this, because when I try to do 
> less /cygdrive/c/Users/Utilisateur/AppData/Roaming/stack/global-project/stack.yaml

it works fine and shows the contents of the file.
[haskell-vim-now-2015-12-01_b.txt](https://github.com/begriffs/haskell-vim-now/files/49217/haskell-vim-now-2015-12-01_b.txt)

**Comment by SimpleX91** [comment]
@ideruga try sed manually (take command from setup.sh). And check it's output. Try to make it work.
Then you have problems with GCC C compiler. Try running "stack install network" and see what it prints.

**Comment by ideruga** [comment]
@SimpleX91 Here's my test:
>  #!/usr/bin/bash
. ./func.sh
DEPS_REGEX='s/extra-deps: \[\]/extra-deps: [cabal-helper-0.6.1.0, pure-cdb-0.1.1]/'
STACK_GLOBAL_CONFIG=$(fix_path $(stack --verbosity 0 path --config-location))
echo $STACK_GLOBAL_CONFIG
sed -i.bak "${DEPS_REGEX}" ${STACK_GLOBAL_CONFIG}

Here's the result:

>/cygdrive/c/Users/Utilisateur/AppData/Roaming/stack/global-project/stack.yaml
: No such file or directorygdrive/c/Users/Utilisateur/AppData/Roaming/stack/global-project/stack.yaml

Now, I just copy the result of the echo into the test.sh file like this:
> #!/usr/bin/bash

>. ./func.sh

>DEPS_REGEX='s/extra-deps: \[\]/extra-deps: [cabal-helper-0.6.1.0, pure-cdb-0.1.1]/'
STACK_GLOBAL_CONFIG=/cygdrive/c/Users/Utilisateur/AppData/Roaming/stack/global-project/stack.yaml
echo $STACK_GLOBAL_CONFIG
sed -i.bak "${DEPS_REGEX}" ${STACK_GLOBAL_CONFIG}

And it works.

I will investigate the C compiler problem this evening (E.T.)

**Comment by begriffs** [comment]
@ideruga any progress with the compiler problem?

**Comment by ideruga** [comment]
Not yet, will take another shot at it tonight.

**Comment by ideruga** [comment]
I made a PR to correct the path issue. I will investigate the compiler problem next.
P.S.: Forking a project from a particular branch (not master) It is way too hard in github...

**Comment by SimpleX91** [comment]
I think it's done. Thanks to @ideruga for testing and corrections!

**Comment by begriffs** [comment]
Nice work guys. I'll merge it.

**Pull request merged**
