### PR TITLE
Fix deprecated `stack path` options

### PR DESCRIPTION
**Pull request by SimpleX91**
Due to latest stack's warnings:
'--local-bin-path' will be removed in a future release.
'--global-stack-root' will be removed in a future release.

### CODE REVIEW

**Comment by begriffs** [comment]
Thanks for keeping everything up to date.

**Comment by SimpleX91** [comment]
Yup, no problem.
Uhm, @begriffs, could you please clear _Issues_ from outdated and obsolete ones?

**Comment by begriffs** [comment]
Sure I'll make a note to look at the issues later and clean out the obsolete ones.

**Comment by SimpleX91** [comment]
Well, you could clean them all. We'll reopen some if necessary. Or even add the info to FAQ. 39 non-relevant issues is just too many for a github repo. =)

**Pull request merged**
