### PR TITLE
Add neovim specific settings and symlinking support

### LINKED ISSUE #87: NeoVim support
How about supporting NeoVim? I'm using it now with haskell-vim-now and most of the time it works fine. It has some problems with NERDTree.

NeoVim provides async features, which could enhance user experience with, for example, automatic async checks with ghc-mod on save.

[Here](https://neovim.io/doc/user/nvim_from_vim.html) described how to easily symlink vim config to nvim's.

### LINKED ISSUE #114: Should HVN make neovim config symlinks if "nvim" is found?
Should HVN make neovim config symlinks if "nvim" is found?
Except for NERDTree, everything works just fine with neovim.

### PR DESCRIPTION
**Pull request by Tehnix**
Backup any existing neovim configuration, and symlink the HVN configuration
into ~/.config/nvim/. 

Also adds some neovim specific settings into the .vimrc, wrapped in checks for
has('nvim'), so they don't affect normal vim.

This closes #87 and closes #114.

### CODE REVIEW

**Comment by SimpleX91** [comment]
@begriffs please, don't merge this.
I'm strongly against messing user's neovim config. It's okay to add nvim specific settings, though. But if user wants to use HVN with NeoVim, then let him do it (semi) manually. It could be nice to add one more script (like `configure_nvim.sh`) and instructions in README to let user know how to run it. Or ask user during installation.
You could, actually, just symlink `~/.config/nvim` to `~/.config/haskell-vim-now/.vim` and `~/.config/haskell-vim-now/.vimrc` to `~/.config/haskell-vim-now/.vim/init.vim`.

**Comment by Tehnix** [comment]
I was under the impression from [https://github.com/begriffs/haskell-vim-now/issues/87](https://github.com/begriffs/haskell-vim-now/issues/87) that you wanted support for Neovim, which is basically what this is? Else I don't know what you mean by,

>Anyway, it's easy to provide nvim support just by symlinking vim config to nvim's. So it could be useful to add checks for nvim in PATH and if it's there - make symlinks.

The script does exactly what it does for VIM, checking for an existing config, backing it up if it exists, and then makes symlinks like is done with VIM. 

For Neovim the symlinking is slightly different in that `init.vim` is located inside the `nvim` folder, so it symlinks `init.vim` to `.config/nvim/init.vim` and the `bundle` and `autoload` folders to `.config/nvim/bundle` and `.config/nvim/autoload`. Plainly symlinking the `.vim` folder to `.config/nvim` would mean adding `init.vim` inside this folder, which is actually adding it inside the `.vim` folder.

That said, if the symlinking being optional is preferred, then I can just remove the symlinking part, and keep the `.vimrc` configuration stuff.

**Comment by SimpleX91** [comment]
I only said that it should not be done during installation by default. Your .vimrc edits for neovim are nice, it would be great to merge them.
Just move installer changes outside of it (to neovim.sh for example). At least it's good to keep such things separated and optional.
Oh, btw it would be great to `git rebase` your changes to make it two commits like "Improve NeoVim support" and "Add script to replace NeoVim config with HVN".
Just my thought though.

**Comment by Tehnix** [comment]
I'll move it into it's own script then :)

Perhaps with a closing remark during the install, like "If you want to use haskell-vim-now for Neovim, you can quickly backup and replace your existing configuration by running <path to script>"?

And I'll do the rebase (once I find out how exactly to do that ._.)

**Comment by SimpleX91** [comment]
I even thought about rewriting parts of installer to Haskell (using Shelly or Turtle), but unfortunately I don't have time for this now. It should be easier to modify Haskell scripts for Haskell developers, shouldn't it? =)

Yup, this remark at the end of installation should be enough. Maybe add some info to README.

**Comment by Tehnix** [comment]
I'll close this in favor of #125.

**Pull request closed without merging**
