### PR TITLE
Add stylish-haskell

### PR DESCRIPTION
**Pull request by igniting**
Run [stylish-haskell](https://github.com/jaspervdj/stylish-haskell) on Haskell buffers every time they are saved.

### CODE REVIEW

**Comment by begriffs** [comment]
Oh good idea, thanks for the pull request. Is there a way to disable the auto-format-on-save though and make the reformatting happen manually on the whole buffer or a visual selection?

**Comment by igniting** [comment]
[stylish-haskell](https://github.com/jaspervdj/stylish-haskell) formats only the import statements and the {-# LANGUAGE #-} pragmas. To use it, we have to call `:%!stylish-haskell`. I added [vim-stylish-haskell](https://github.com/nbouscal/vim-stylish-haskell) which runs it automatically on save. I can remove the vim plugin, if it seems a better option.

**Comment by igniting** [comment]
I removed the vim plugin. Users would have to call `%!stylish-haskell` to run stylish-haskell.

**Comment by begriffs** [comment]
Thank you! What do you think about making it the default format program, so when you press `gq` on a selection it gets used (the format program is currently `par`)?

https://github.com/begriffs/haskell-vim-now/blob/master/.vimrc#L28

Maybe use stylish-haskell only for Haskell buffers and par for all the others.

**Comment by igniting** [comment]
That sounds great! I'll update the PR.

**Comment by igniting** [comment]
Updated

**Comment by begriffs** [comment]
Finally can you please add a note in the readme explaining this feature?

**Comment by igniting** [comment]
Done

**Comment by begriffs** [comment]
Hey does this actually work for you? When I make a small selection and press `gq` I get an error

```
Language.Haskell.Stylish.Parse.parseModule: could ¬parse <unknown>:
  ParseFailed (SrcLoc "<unknown>.hs" 7 1) "TemplateHaskell is not enabled"
```

The region I selected didn't have any template haskell in it, so I'm not sure what's going on or if you get a similar error.

**Comment by igniting** [comment]
It works fine for me. Do you encounter this for every file? Someone had reported a similar error upstream https://github.com/jaspervdj/stylish-haskell/issues/3 , but that was long back.

**Comment by begriffs** [comment]
Maybe it was just the region I happened to select. It worried me that maybe it was breaking all the time for everyone, but if it works OK for you then it's fine. I'll wait until someone else submits an issue before looking into it further.

**Pull request merged**
