### PR TITLE
Fix installation on Mac OS X (homebrew/dupes/make and pointfree)

### LINKED ISSUE #134: Mac OS X: brew install fails
The `brew install` from `setup.sh` line 22 fails with the following message:

    --- Installing with homebrew...
    Error: No available formula with the name "make"

As a result none of the software in `BREW_LIST` gets installed.

    BREW_LIST="git make vim ctags"

Due to other complaints from `setup.sh` I did a manual install (using homebrew) of vim 7.4 and exuberant ctags. There were no complaints about git or make so I haven't replaced the ones from Apple.

    git version 2.5.4 (Apple Git-61)
    GNU Make 3.81

I'm on Mac OS X 10.11.2 with Xcode 7.2 installed. Perhaps without Xcode I wouldn't have had git and make installed already(?).

As a side note it also seems to me that if this issue is fixed the ctags issue discussed on https://github.com/begriffs/haskell-vim-now/wiki/Installation-Troubleshooting should go away by itself.

### PR DESCRIPTION
**Pull request by bjornbm**
9667c75 fixes #134.
20b5f02 fixes the problem I reported on #121 by means analogous to the fix of #132.

### CODE REVIEW

**Comment by bjornbm** [comment]
Commit 20b5f02 also fixes the problem I reported on #121 with a fix analogous to that of #132.

**Comment by begriffs** [comment]
Thank you! I appreciate your debugging and fixing the problems.

**Comment by bjornbm** [comment]
My pleasure. I appreciate the work you put into making Haskell in Vim awesome! :+1:

**Comment by jship** [comment]
Just an FYI, I'm working with @bosu to get hscope and its dependencies on Stackage.

When that is done, I'll test haskell-vim-now against the first nightly that supports hscope, with the end goal of using LTS instead of the 2015-12-08 pinned nightly Stackage version and the specific pointful/pointfree versions.

**Comment by mikowiec** [comment]
Error message has obtained during installation:
   "No available formula with the name "homebrew/dupes/make" "
  and "brew info make" was fault

I've performed installation of brew make next way:
"brew install https://raw.githubusercontent.com/Homebrew/homebrew-dupes/master/make.rb"

**Comment by begriffs** [comment]
Let's continue discussion of the brew error in issue #166

**Pull request merged**
