### PR TITLE
Create config dir if it does not exist

### PR DESCRIPTION
**Pull request by begriffs**
@jacksonja would you try this on your machine and see if it works?

### CODE REVIEW

**Comment by jacksonja** [comment]
This worked for me. Thanks.

**Comment by begriffs** [comment]
Sorry we broke it in the first place. We should add continuous integration to the project where it tries to run the installer on a bunch of architectures.

**Comment by SimpleX91** [comment]
My bad! Didn't think about it. I'm using Linux (Fedora 23), and ".config" is created automatically by DE, I think (and some other tools already follow XDG papers).
And we don't have cygwin support yet, need someone to describe install process.

At least now it's easier to add platform support and fix bugs, I hope ;P

**Comment by begriffs** [comment]
Oh yeah it's way easier. I'm loving the new scripts.

**Pull request merged**
