### PR TITLE
Fix for latest stack

### PR DESCRIPTION
**Pull request by pavlosgi**

### CODE REVIEW

**Comment by begriffs** [comment]
Thanks! Will this work on older Stack as well? If not maybe we should add a check that the Stack version is high enough.

**Comment by pavlosgi** [comment]
No I don't think it will work so yes we should do that I'll add it in

**Comment by pavlosgi** [comment]
Done

**Comment by begriffs** [comment]
Smart, that works.

What's that new file named `0.1.9.0` all about?

**Comment by pavlosgi** [comment]
Removed that it's redundant

**Comment by SX91** [comment]
Or maybe we should ask user to install latest stack version? And check that version in `setup.sh`.

**Comment by begriffs** [comment]
I'm going to merge this to be on the safe side. Later on if we like we can ask the user to install the latest slack version.

**Pull request merged**
