### PR TITLE
Add option to force sync on updates.

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
Closes https://github.com/begriffs/haskell-vim-now/issues/213.

### CODE REVIEW

**Comment by begriffs** [comment]
Thanks for the contribution! ❤️ 

Looks like we need to change the continuous integration script to pipe `yes` to the installer https://github.com/begriffs/haskell-vim-now/blob/master/.travis.yml#L37 or else the build breaks waiting for input.

**Comment by ryanpcmcquen** [comment]
We could also just send an enter key (which would bypass the case statement). Which would you prefer?

**Comment by begriffs** [comment]
There's actually a unix command called yes, so you could do

```bash
yes | bash install.sh
```

Also could you include the change as another commit on this pull request rather than in a new pull request?

**Comment by ryanpcmcquen** [comment]
I can also rebase those, if you just want one commit. 👍

**Comment by begriffs** [comment]
Thanks that seems to work nicely. Don't worry about rebasing, github now provides me the option to squash and merge right in the GUI.

One more thought... maybe the script should not prompt the user or do a git reset when there are no local changes. You could test the return code from `git status --quiet` maybe. In fact with that change we would not have to pipe `yes` into the installer on Travis because it should be clean to pull and won't require a prompt.

**Comment by ryanpcmcquen** [comment]
OK, I'll put something together.

**Comment by begriffs** [comment]
Nice work! Just tested it out with and without local changes and it works great.

**Comment by ryanpcmcquen** [comment]
Thanks, worked great here too. :smiley_cat:

**Pull request merged**
