### PR TITLE
Fedora requires installing 'par'

### PR DESCRIPTION
**Pull request by tsoernes**
Also, I suggest detecting if neovim is installed and if so then skip installing vim.

### CODE REVIEW

**Comment by begriffs** [comment]
Thanks for the improvement. I don't see the part about the neovim check in the commits -- are you still working on it?

**Comment by tsoernes** [comment]
No, I'm unsure how to do it in a way that works across platforms

**Comment by begriffs** [comment]
The other case statements use `cmdpkg par par`, is there a reason to do it differently for fedora?

**Comment by begriffs** [comment]
@tsoernes any opinion about my cmdpkg question?

**Comment by tsoernes** [comment]
I'm not entirely sure why some packages are echoes and some are called with `cmdpkg`. As long as the package name is mentioned it's fine, bonus points if the installer script automatically calls `dnf install` for the required packages.

**Comment by begriffs** [comment]
Thanks again for pointing this issue out. I fixed it by installing par more uniformly on all platforms.

**Pull request closed without merging**
