### PR TITLE
Use identical stack snapshot for setup and install

### PR DESCRIPTION
**Pull request by harendra-kumar**

### CODE REVIEW

**Comment by SimpleX91** [comment]
We could even remove specific version and leave it `--resolver lts`.

**Comment by harendra-kumar** [comment]
We can certainly try that and see how it goes. There is an uncertainty in that though. A fixed version allows us to test and certify that it works.

Ideally we should perhaps use the user's global project resolver instead of an explicit resolver so that we do not end up unnecessarily installing a new compiler in some cases. But since things are changing rapidly that might be set to an old version and may not always work.

**Comment by SimpleX91** [comment]
But if version in stack global config is lower than 5.x, then what? Better to install new compiler than leave user with helper binaries build errors IMO.

**Comment by begriffs** [comment]
This change is better than what we had before. Maybe someday we can check the global config and match that.

**Pull request merged**
